build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/zlib.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/zlib.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/libwebp.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/libwebpdemux.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/libwebpmux.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/libsharpyuv.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/libwebp.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/libwebpdemux.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/libwebpmux.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/libsharpyuv.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/aom.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/aom.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vpx.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-encode-cli/ffbuild/config.mak: build/inst/base/lib/libmp3lame.a
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-encode-cli/ffbuild/config.mak: build/inst/thr/lib/libmp3lame.a
